### ISSUE TITLE
Is this library considering https://openjdk.org/jeps/472 (JEP 472: Prepare to Restrict the Use of JNI)

### ISSUE THREAD

**Issue by oscarvarto** [chitralverma/scala-polars#138]
Java 24 GA is around the corner.
Is this library making good use of JNI according to the direction the JDK is taking?

**Comment by chitralverma** [comment]
this library currently supports all LTS from 8 to 21. if you're referring to the use of panama, I tried it as an internal test but that shift will require me to drop support for all previous versions.

to support JDK 24, most probably I'll add some configs in the build to continue using JNI as is to continue compatibility with JDK >=8
