### ISSUE TITLE
Add .rows function to DataFrame

### ISSUE THREAD

**Issue by jarredparrett** [chitralverma/scala-polars#63]
Wondering if there is any consideration for adding a .rows function to the `org.polars.scala.polars.api.DataFrame` implementation. 

https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.rows.html

**Comment by chitralverma** [comment]
let me check this out

**Comment by jarredparrett** [comment]
Started taking a look at it, and the underlying function is [row_tuples](https://github.com/pola-rs/polars/blob/38d016b61971c1ce3789fced9a7aa519983d5de9/py-polars/src/dataframe.rs#L739). 

Happy to raise a PR to implement it.

**Comment by chitralverma** [comment]
@jarredparrett my bad for the late response, please raise a PR for this if its not too much. thanks a lot
